
export const mockPatientViewModel = {
    items: [
        {
            parcticeId: 6,
            patientId: 98,
            classType: "SP",
            chartNumber: "1",
            staffId: 42,
            referralSource: "FRIEND",
            refDoctorId: 0,
            recordStatus: "A",
            timeStamp: "2019-10-25T00:00:00",
            lastUser: 4,
            createStamp: "2019-10-25T00:00:00",
            createUser: 4,
            registrationComplete: "Y",
            dnLastName: "Aaron",
            dnFirstName: "Alice",
            dnMiddleName: "B",
            dnNameSuffix: null,
            dnSSN: "100000206",
            dnSex: "F",
            dnDOB: "1970-02-07T00:00:00",
            dnHomePhone: "9165555555",
            dnPersonNumber: "1",
            patInfoReleaseOnFile: null,
            registrationDate: "2006-04-28T00:00:00",
            favoritePharmacyId: 207,
            dnSortChartNumber: "1",
            dnSortPersonNumber: "1",
            frontImageSId: 0,
            backImageSId: 0,
            formularyPlanId: null,
            formularyGroupId: null,
            formularyState: "",
            numDisclosureReports: 0,
            lastDiscReportDateStamp: null,
            lastMarkerNumber: 0,
            hl7Updated: null,
            chartScanned: false,
            frontImageFileId: null,
            backImageFileId: null,
            takingMedsIndicator: "U",
            takingMedsConfirmationUser: 0,
            takingMedsConfirmationStamp: null,
            duplicatePersonId: 0,
            deactivationNote: null,
            deactivationDate: "0001-01-01T00:00:00",
            deactivationReason: null,
            deactivationUser: 0,
            confidential: false,
            confidentialDate: "0001-01-01T00:00:00",
            confidentialUser: 0,
            confidentialReason: null,
            exemptFromReporting: false,
            recallMethod: "Paper",
            clinicalChangeTimeStamp: null,
            vfcEligibilityCode: null,
            vfcEffectiveDate: "0001-01-01T00:00:00",
            mappedAtImmuRegistry: true,
            riskLevel: null,
            secondaryPharmacyId: 0,
            primaryCareProviderId: 42,
            careCoordinatorId: 0,
            genderIdentity: null,
            genderIdentityFreeText: null,
            sexualOrientation: null,
            sexualOrientationFreeText: 0,
            dnMobilePhone: null,
            publicityCode: null,
            publicityCodeEffectiveDate: "0001-01-01T00:00:00",
            frontImageScanStamp: null,
            backImageScanStamp: null,
            frontImageScanUserId: 0,
            backImageScanUserId: 0,
        }
    ],
    previousSeed: "1",
    nextSeed: "1",
    batchSize: 1
};
export const mockPatientSearchData = {
    items: [
        {
            sortOrder: "patientid",
            searchText: 98,
            assignedProviderId: '',
        }

    ],

};
